### ISSUE TITLE
Error []main.OperacionTicket 

### ISSUE THREAD

**Issue by ifmael** [parzibyte/ejemplos-plugin-impresoras-termicas-v2#1]
Estoy utilizando windos 10,  he instalado la impresora de ticket y he impreso una pagina de prueba.

Tras instalar el plugin, compatir la impresosa,he probado hacer una impresión de prueba  y obtengo este fallo ( para los ejemplos 1, 2,4):

`2/25/2021, 9:21:57 PM Error. La respuesta es: Error en el servidor: json: cannot unmarshal object into Go value of type []main.OperacionTicket`

Y este otro para el ejemplo "Imprimir texto con acentos"

`2/25/2021, 9:26:20 PM Error. La respuesta es: [object Promise]`

**Comment by parzibyte** [comment]
Para el caso de los acentos, ya lo he corregido en https://github.com/parzibyte/ejemplos-plugin-impresoras-termicas-v2/commit/4923aebf6ce7631801bb6e8aed62a8b766d5fe34
En cuanto a los otros ejemplos, acabo de probar y todos funcionan perfectamente. Asegúrese de estar ejecutando la última versión del plugin y el conector de JS

**Comment by ifmael** [comment]
Gracias por tu rápida respuesta y darte la gracias por el plugin.

Creo que estaba ocurriendo este problema porque tenía las 2 versiones del plugins corriendo.
